---
req_cn: "{{private_host_ipv4}}@{{lookup('pipe', 'date +%s')}}"
sans: "IP:{{private_host_ipv4}},IP:{{kube_service_ip}},DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.{{ dns_domain}},DNS:{{ inventory_hostname }}"

accounts: [ 'controller-manager', 'scheduler', 'kubectl', 'kubelet', 'kube-proxy' ]