---

- name: "downloading easyrsa from google"
  local_action:
    get_url
      url="https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz"
      dest="downloads/easy-rsa.tar.gz"

- local_action:
    unarchive
      src="{{local_download_dir}}/easy-rsa.tar.gz"
      dest="{{local_download_dir}}/"
      creates={{easyrsa}}
      copy=no

- local_action: command ./easyrsa {{item}}
  args:
   chdir: "{{easyrsa_dir}}"
  with_items:
    - "init-pki"
    - "--batch --req-cn={{ req_cn }} build-ca nopass"
    - "--subject-alt-name=\"{{ sans }}\" build-server-full \"{{ inventory_hostname }}\" nopass"
    - "build-client-full kubelet nopass"
    - "build-client-full kubecfg nopass"