---

- command: touch {{known_tokens}} creates="{{known_tokens}}"


- shell: |
    account=$(grep {{ item }} {{ known_tokens }} 2>/dev/null)
    if [ -n "$account" ]
    then
      token=`echo $account | awk -F, '{print $1}'`
      key=`echo $account | awk -F, '{print $2}'`
      stat=present
    else
      token=$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64 | tr -d "=+/" | dd bs=32 count=1 2>/dev/null)
      key="{{ item }}"
      stat="generated"
    fi
    csv="$token,$key,$key"
    fact="$key: $token"
    echo '{ "csv": "'"$csv"'", "token": "'"$token"'", "name": "'"$key"'", "stat": "'"$stat"'" }'
  register: tokens
  with_items: "{{ accounts }}"
  changed_when: tokens.stdout.find('generated') != -1
  name: generate tokens into csv and fact formats

#- debug: var=tokens

- set_fact:
    tokens: "{{ tokens.results | map(attribute='stdout')| map('from_json') | list }}"
  name: "map tokens.results as json"

- lineinfile: >
    dest="{{known_tokens}}"
    line="{{ item.csv }}"
    regexp="{{ item.name }}"
    create=yes
  with_items: "{{ tokens }}"
#  delegate_facts: true
#  delegate_to: "{{ groups['masters'][0] }}"
