---

- include: gen_token.yml
  name: generate tokens
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: yes

- local_action: stat path="{{certs_dir}}"
  register: pki_dir
  become: no

- name: generate certs
  include: gen_certs.yml
  run_once: yes
  become: no
  when: pki_dir.stat.exists == false