---
- hosts: masters
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts:
    - nodes
    - masters
  become: yes
  roles:
    - flannel
  tags:
    - nodes

- hosts: masters
  become: yes
  roles:
    - master
  tags:
    - masters
    - k8s

- hosts: nodes
  become: yes
  roles:
    - node
  tags:
    - join
    - k8s

- hosts: glusters
  become: yes
  roles:
    - gluster
    - gluster_vol
  tags:
    - pv

- hosts: kube-master
  become: yes
  roles:
    - elasticsearch
  tags:
    - es

- hosts: masters
  become: yes
  roles:
    - "kube-addons"
  tags:
    - k8s
    - addons

# vim:ft=ansible:
