---
- hosts: kube-master
  become: yes
  tasks:
    - file: path=/github/elasticsearch-cluster state=directory
    - git: repo=https://github.com/jaohaohsuan/kubernetes-elasticsearch-cluster.git
           dest=/github/elasticsearch-cluster
          
    - command: "kubectl apply -f {{item}}"
      args:
        chdir: /github/elasticsearch-cluster
      with_items:
        - "service-account.yaml"
        - "es-discovery-svc.yaml"
        - "es-svc.yaml"
        - "es-master-rc.yaml"
      changed_when: false

    - shell: |
        kubectl get po | grep es-master
      register: result
      until: result.stdout.find('Running')
      changed_when: false
      retries: 10
      delay: 30

    - command: kubectl apply -f es-client-rc.yaml
      args:
        chdir: /github/elasticsearch-cluster

    - shell: |
        kubectl get po | grep es-client
      register: result
      until: result.stdout.find('Running')
      changed_when: false
      retries: 10
      delay: 30

    - command: kubectl apply -f es-data-rc.yaml
      args:
        chdir: /github/elasticsearch-cluster