---

- name: "Copy GlusterFS package to remote machines"
  copy: src=files dest=/tmp/ mode=0744

- name: "Install all GlusterFS packages"
  shell: dpkg -i * chdir=/tmp/files

- service: name=glusterfs-server state=started enabled=yes

- name: "Create mount folder and brick"
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_mnt_dir }}"
    - "{{ gluster_brk_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_vlm_name }}"
    brick: "{{ gluster_brk_dir }}"
    replicas: 2
    cluster: "{{ groups.glusters | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: "Copy GlusterFS client and dependency package to kubernetes node machines."
  copy: "src=roles/gluster/files/{{ item[1] }} dest=/tmp/gluster_client/ mode=0744"
  delegate_to: "{{ item[0] }}"
  with_nested:
    - "{{ groups.nodes }}"
    - [ 'glusterfs-client_3.6.9.deb', 'glusterfs-common_3.6.9.deb', 'libaio1_0.3.109.deb', 'libdevmapper-event_1.02.1.deb', 'libibverbs1_1.1.7.deb', 'liblvm2app2_2.02.98.deb', 'librdmacm1_1.0.16.deb', 'attr1_2.4.47.deb' ]

- name: "Install all GlusterFS packages"
  shell: dpkg -i * chdir=/tmp/gluster_client/
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups.nodes }}"
  run_once: true
#- name: Ensure Gluster volume is mounted.
#  mount:
#    name: "{{ gluster_mnt_dir }}"
#    src: "{{ inventory_hostname }}:/{{ gluster_vlm_name }}"
#    fstype: glusterfs
#    opts: "defaults,_netdev"
#    state: mounted
