---

- name: "Copy GlusterFS package to remote machines"
  copy: src=files dest=/tmp/ mode=0744

- name: "Install all GlusterFS packages"
  shell: dpkg -i * chdir=/tmp/files

- service: name=glusterfs-server state=started enabled=yes

- name: "Create mount folder and brick"
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_mnt_dir }}"
    - "{{ gluster_brk_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_vlm_name }}"
    brick: "{{ gluster_brk_dir }}"
    replicas: 2
    cluster: "{{ groups.glusters | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true


#- name: Ensure Gluster volume is mounted.
#  mount:
#    name: "{{ gluster_mnt_dir }}"
#    src: "{{ inventory_hostname }}:/{{ gluster_vlm_name }}"
#    fstype: glusterfs
#    opts: "defaults,_netdev"
#    state: mounted
