apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
  labels:
    name: nodejs-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: web-service
