---

- set_fact:
    flannel_config: "{{ lookup('template', 'config.json.j2')}}"

- command: "etcdctl get /{{dns_domain}}/network/config"
  register: result
  changed_when: result.rc != 0
  ignore_errors: true

- name: "config flannel"
  command: "etcdctl set /{{dns_domain}}/network/config {{flannel_config}}"
  when: '{{flannel_config}} not in result.stdout|default("")'
