---

- set_fact:
    flannel_config: "{{lookup('template', 'config.json.j2')}}"
  name: read flannel config from template

- command: "etcdctl get /{{dns_domain}}/network/config"
  register: result
  changed_when: result.rc != 0
  ignore_errors: true
  name: "get /{{dns_domain}}/network/config"

- name: "config flannel with {{flannel_config}}"
  command: "etcdctl set /{{dns_domain}}/network/config {{flannel_config}}"
  when: '{{flannel_config}} not in result.stdout|default("")'
