---

- apt: name=etcd state=present
  name: install etcd

- lineinfile: dest=/etc/default/etcd line='ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'

- lineinfile: dest=/etc/default/etcd line='ETCD_ADVERTISE_CLIENT_URLS="http://{{private_host_ipv4}}:2379"'

- service: name=etcd state=started

- wait_for: 'host="{{private_host_ipv4}}" port=2379 delay=3'

- include: "flannel-config.yml"
