---

- name: "download flannel github release tag {{ flannel_version }}"
  local_action:
    get_url
      url="https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="downloads/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
  become: no
  run_once: true

- local_action:
    unarchive
      src="{{local_download_dir}}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="{{local_download_dir}}/"
      copy=no
      creates="{{local_download_dir}}/flannel-{{ flannel_version }}/flanneld"
  become: no
  run_once: true

- name: "copy binaries to /usr/bin"
  copy:
    src: downloads/flannel-{{ flannel_version }}/{{ item }}
    dest: /usr/bin/{{ item }}
    mode: "0754"
  with_items:
    - flanneld

- copy: src=flannel.service dest=/lib/systemd/system
  name: install flannel service
  notify:
    - service restart flannel
    - service restart docker

- template: src=flannel.j2 dest=/etc/default/flannel
  name: config

- service: name=flannel state=started enabled=yes
  register: flannel_started

- service: name=docker state=restarted
  when: flannel_started.changed

#- debug: var=flanneld_started