---

- name: "download flannel github release tag {{ flannel_version }}"
  local_action:
    get_url
      url="https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="downloads/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
  become: no
  run_once: true

- local_action:
    unarchive
      src="{{local_download_dir}}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="{{local_download_dir}}/"
      copy=no
      creates="{{local_download_dir}}/flannel-{{ flannel_version }}/flanneld"
  become: no
  run_once: true
  name: "extract flannel-{{ flannel_version }}-linux-amd64.tar.gz"

- name: "copy binaries to /usr/bin"
  copy:
    src: downloads/flannel-{{ flannel_version }}/{{ item }}
    dest: /usr/bin/{{ item }}
    mode: "0754"
  with_items:
    - flanneld
    - mk-docker-opts.sh

- copy: src=flannel.service dest=/lib/systemd/system
  name: install flannel service

- template: src=flannel.j2 dest=/etc/default/flannel
  name: copy environment file /etc/default/flannel

- file: path=/etc/systemd/system/docker.service.d state=directory mode=0755
  name: docker drop-ins directory must be present

- copy: src=flannel.conf dest=/etc/systemd/system/docker.service.d/flannel.conf mode=0755
  name: add flannel.conf drop-ins

- service: name=flannel state=started enabled=yes

- shell: |
    ip link set docker0 down &>2 || true
    brctl delbr docker0 down &>2 || true
  name: clean up docker0
  become: yes
  notify:
    - daemon realod
    - restart docker