---

- file: path=/tmp/jenkins state=directory
- copy: src=service.yml dest=/tmp/jenkins/service.yml
- copy: src=rc.yml dest=/tmp/jenkins/rc.yml

- name: apply jenkins service
  shell: |
    kubectl apply -f /tmp/jenkins
  become: yes
  register: apply_jenkins_result
  changed_when: false

- name: find jenkins pod
  shell: |
    kubectl get po -l name=jenkins --no-headers | grep -i 'running' | awk '{ print $1}'
  register: get_jenkins_po
  until: "get_jenkins_po.rc == 0"
  changed_when: false
  retries: 1000
  delay: 5
  become: yes

- set_fact:
    jenkins_pod: "{{ get_jenkins_po.stdout }}"
    jenkins_pre_install_plugins: "[ 'ansicolor', 'github', 'kubernetes' ]"

- name: list plugins
  become: yes
  shell: |
    kubectl exec -it {{ jenkins_pod }} -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ list-plugins | awk '{ print $1}'
  register: jenkins_plugins
  changed_when: false

- name: install plugins
  become: yes
  shell: |
    kubectl exec -it {{ jenkins_pod }} -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{ item }}
  register: jenkins_plugins_pre_installation_result
  when: "{{ item not in jenkins_plugins.stdout_lines }}"
  with_items: "{{ jenkins_pre_install_plugins }}"

- name: list plugins which need update
  become: yes
  shell: |
    kubectl exec -it {{ jenkins_pod }} -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ list-plugins | grep -e '(.*)' | awk '{ print $1}'
  register: jenkins_plugins
  changed_when: false

- name: upgrade plugins
  become: yes
  shell: |
    kubectl exec -it {{ jenkins_pod }} -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ install-plugin {{ item }}
  with_items: "{{ jenkins_plugins.stdout_lines }}"
  when: "jenkins_plugins.stdout_lines | length > 0"
  register: jenkins_plugins_upgrade_result

- name: safe-restart jenkins master
  debug: var=item
  notify: safe-restart jenkins
  when: (item.skipped == false)
  with_items: "{{ jenkins_plugins_pre_installation_result.results + jenkins_plugins_upgrade_result.results }}"
  
- name: jenkins health check
  become: yes
  shell: |
    kubectl exec -it {{ jenkins_pod }} -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://127.0.0.1:8080/ version
  register: jenkins_helth_check
  until: jenkins_helth_check.rc == 0
  retries: 1000
  delay: 5
  changed_when: false

- debug: msg="jenkins version {{ jenkins_helth_check.stdout }}"
  when: jenkins_helth_check.rc == 0


