---

#- include: gluster-client.yml
- include: install-additional-packages.yml

- file: path=/etc/kubernetes/manifests state=directory mode=0644
  name: manifests directory

- copy: src="{{easyrsa_dir}}/pki/ca.crt" dest=/srv/kubernetes/ca.crt mode=0644

- include: tokens.yml
  name: gather tokens

- file: path="/var/lib/{{item}}" state=directory
  with_items: "{{services}}"

- template: src="{{item}}.kubeconfig.j2" dest="/var/lib/{{item}}/kubeconfig"
  with_items: "{{services}}"

- copy: >
    src="{{ kube_binaries_dir }}/{{ item }}"
    dest="/usr/bin/{{ item }}"
    mode=0744
  with_items: "{{binaries}}"

- copy: src="{{item}}.service" dest="/lib/systemd/system/{{item}}.service"
  with_items: "{{services}}"

- template: src="{{item}}.j2" dest="/etc/default/{{item}}"
  with_items: "{{services}}"

- service: name="{{item}}" state=started enabled=yes
  with_items: "{{services}}"
