---

#- include: gluster-client.yml

- copy: src="{{easyrsa_dir}}/pki/ca.crt" dest=/srv/kubernetes/ca.crt mode=0644

- include: tokens.yml
  name: gather tokens

- file: path="/var/lib/{{item}}" state=directory
  with_items: "{{services}}"

- template: src="{{item}}.kubeconfig.j2" dest="/var/lib/{{item}}/kubeconfig"
  with_items: "{{services}}"

- copy: >
    src="{{ kube_binaries_dir }}/{{ item }}"
    dest="/usr/bin/{{ item }}"
    mode=0744
  with_items: "{{binaries}}"

- copy: src="{{item}}.conf" dest="/etc/init/{{item}}.conf"
  with_items: "{{services}}"

- template: src="{{item}}.j2" dest="/etc/default/{{item}}"
  with_items: "{{services}}"

- service: name="{{item}}" state=started
  with_items: "{{services}}"