---
- file: path=/github/elasticsearch-cluster state=directory

- git: repo=https://github.com/jaohaohsuan/kubernetes-elasticsearch-cluster.git
       dest=/github/elasticsearch-cluster
       version=fc5c8d7ad3f97d71e3e54fcc0e5be704f13ee96e
  become: yes

- command: "kubectl apply -f {{item}}"
  args:
    chdir: /github/elasticsearch-cluster
  with_items:
    - "service-account.yaml"
    - "es-discovery-svc.yaml"
    - "es-svc.yaml"
    - "es-master-rc.yaml"
  changed_when: false

- shell: |
    kubectl get po | grep es-master
  register: result
  until: "'Running' in result.stdout"
  changed_when: false
  retries: 1000
  delay: 60

- command: kubectl apply -f es-client-rc.yaml
  args:
    chdir: /github/elasticsearch-cluster

- shell: |
    kubectl get po | grep es-client
  register: result
  until: "'Running' in result.stdout"
  changed_when: false
  retries: 1000
  delay: 60

- command: kubectl apply -f es-data-rc.yaml
  args:
    chdir: /github/elasticsearch-cluster