---
- apt: name=linux-generic-lts-vivid state=present
  name: install newer kernel

- lineinfile: dest=/etc/default/grub state=present line="GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"" regexp="cgroup_enable"
  register: edit_grub
  name: add support memory limit

- command: update-grub
  when: edit_grub.changed
  name: "update-grub"

- name: restart machine
  command: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: edit_grub.changed

- name: waiting for server to come back
  local_action: >
    wait_for host={{ ansible_ssh_host | default(inventory_hostname) }}
    state=started
    port=22
    delay=30
    timeout=300
    connect_timeout=15
  become: no
  when: edit_grub.changed