---

- group: name=docker gid=999 state=present

- include: "cgroup-enable.yml"
  name: enable cgroup

- command: which docker
  register: docker_exist
  changed_when: false
  ignore_errors: true

- shell: |
    curl -fsSL https://get.docker.com/ | sh
  become: yes
  name: install docker
  when: docker_exist.rc != 0

- include: "flannel-config.yml"

- user: name={{ ansible_user }} shell=/bin/bash groups=docker append=yes
  become: yes
  name: "add {{ ansible_user }} to docker group"