---

- include: "cgroup-enable.yml"
  name: enable cgroup

- command: which docker
  register: docker_exist
  changed_when: false

- shell: |
    curl -fsSL https://get.docker.com/ | sh
  become: yes
  name: install docker
  when: docker_exist.rc != 0

- include: "flannel-config.yml"
  when: docker_exist.rc == 0
  
- user: name={{ ansible_user }} group=docker
  name: "add {{ ansible_user }} to docker group"