---

- name: download Kubernetes github release
  local_action:
    get_url
      url=https://github.com/kubernetes/kubernetes/releases/download/{{ kube_release_ver }}/kubernetes.tar.gz
      checksum="{{kube_release_checksum}}"
      dest="{{local_download_dir}}/kubernetes-{{ kube_release_ver }}.tar.gz"

- local_action:
    unarchive
      src="{{local_download_dir}}/kubernetes-{{ kube_release_ver }}.tar.gz"
      dest="{{local_download_dir}}/"
      creates="{{local_download_dir}}/kubernetes/README.md"
      copy=no

#- debug: var=server_bin
- name: "extract Kubernetes binaries"
  local_action:
    unarchive
      src="{{local_download_dir}}/kubernetes/server/kubernetes-server-linux-amd64.tar.gz"
      dest="{{ local_download_dir }}/kubernetes/server/"
      creates="{{kube_binaries_dir}}/hyperkube"
      copy=no